services:
  - name: vault
    image: vault:1.6.0
    command: ["/bin/vault", "server", "-config", "/var/run/config/vault"]
    capabilities:
      - CAP_SETUID
      - CAP_SETGID
      - CAP_IPC_LOCK
    binds:
      - /var/run/config/vault:/var/run/config/vault
      - /etc/resolv.cluster:/etc/resolv.conf
    runtime:
      mkdir:
        - /var/run/config/vault
