---
services:
  - name: nomad
    image: nomad:0.12.4
    capabilities:
      - CAP_CHOWN
      - CAP_SYS_ADMIN
    command: ["/bin/nomad", "agent", "-config", "/etc/nomad", "-config", "/var/run/config/nomad"]
    binds:
      - /etc/nomad:/etc/nomad
      - /etc/resolv.cluster:/etc/resolv.conf
      - /var/persist:/var/persist
      - /var/run:/var/run
    runtime:
      mkdir:
        - /var/run/config/nomad
        - /var/persist/nomad
files:
  - path: etc/nomad/25-base.hcl
    source: components/nomad/25-base.hcl
    mode: "0644"
    optional: false
